#!/bin/bash
#f=$(ps axc|grep cdevGateway)
#if [ "$f" = "" ]
#then
# CDEV not available anymore for Scientific Linux 5
#	echo "Starting cdevGateway on localhost"
#	export CDEV_NAME_SERVER=`uname -n` 
#	export CDEVDDL=$SLSBASE/sls/config/ddl/SLS.cdl
#	${SLSBASE}/bin/rsvcServer &
#	${SLSBASE}/bin/cdevGateway &
#fi
export EPICS_CA_ADDR_LIST=127.0.0.1
export EPICS_CA_AUTO_ADDR_LIST=no
SV
