#!/bin/bash

CURRENTDIR=`pwd`

# Resolve symlinks
BASEDIR=$0
while [ -h "$BASEDIR" ]; do
    ls=`ls -ld "$BASEDIR"`
    link=`expr "$ls" : '^.*-> \(.*\)$' 2>/dev/null`
    if expr "$link" : '^/' 2> /dev/null >/dev/null; then
        BASEDIR="$link"
    else
        BASEDIR="`dirname "$BASEDIR"`/$link"
    fi
done
BASEDIR=`dirname "$BASEDIR"`
BASEDIR=$(cd $BASEDIR; pwd)
echo $BASEDIR

SCRIPTNAME=`basename ${0}`

LIB_DIR=`find $BASEDIR/../lib -name "*.jar"`
LIB_DIR=`echo $LIB_DIR | sed -e 's/ /:/g'`

CLASSPATH=$LIB_DIR

ARGUMENTS=
VM_ARGUMENTS=
for i in $@
do
        if [ `expr $i : '-D.*'` != '0' ] ;then
                # Extract VM options
                VM_ARGUMENTS="$VM_ARGUMENTS $i"
        else
                ARGUMENTS="$ARGUMENTS $i"
        fi
done

# Execute java

cd $BASEDIR/../etc
java $VM_ARGUMENTS -cp $CLASSPATH ch.psi.synopview.SV $ARGUMENTS
